// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "deeplens-20180905082443--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dwusty9fxmujq.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:57e78dc6-d499-439e-88a4-7d7d619c81aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NL72FvzUg",
    "aws_user_pools_web_client_id": "1q025qh2f0t3cilk5ic9stb3rr",
    "aws_appsync_graphqlEndpoint": "https://pqhsbdstnfbqvj5sughtrj7vay.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-44mwmpanj5a5fjajolctbzmptq"
};


export default awsmobile;
